---
title: "R Notebook"
author: Casey Breen 
---



```{r}
library(tidyverse)
library(gompertztrunc)
library(cowplot)
library(broom)
```


```{r}
set.seed(5)
results <- list()
i = 1


for (start_year in c(1865:1880)) for (window_width in c(1:30)) {

  
  sim_data <- gompertztrunc::gompertztrunc_simu(n=200000, formula = death_age ~ sex, coefs = c('sex'=-0.2), dummy=c(TRUE)) %>% 
    mutate(byear = 1800) %>% 
    mutate(dyear = byear + floor(death_age))
  
  sim_data_trunc <- sim_data %>% 
    filter(dyear >= start_year & dyear <= start_year + window_width)
  
  adj_factor <- 200000/nrow(sim_data_trunc)
  
  sim_data <- gompertztrunc::gompertztrunc_simu(n = adj_factor*200000, formula = death_age ~ sex, coefs = c('sex'=-0.2), dummy=c(TRUE)) %>%
    mutate(byear = 1800) %>% 
    mutate(dyear = byear + floor(death_age))
  
  sim_data_trunc <- sim_data %>% 
    filter(dyear >= start_year & dyear <= start_year + window_width)
  
  lm_model <- lm(death_age~sex, data = sim_data_trunc)
  
  results[[i]] <- tibble(coef = summary(lm_model)$coefficients["sex","Estimate"],
                         se = summary(lm_model)$coefficients["sex","Std. Error"],
                         start_year = start_year,
                         window_width = window_width,
                         n = nrow(sim_data_trunc)) 
  
  
  i = i + 1 
  cat(i)
  
} 

sim_data <- gompertztrunc::gompertztrunc_simu(n=365000, formula = death_age ~ sex, coefs = c('sex'=-0.2), dummy=c(TRUE)) %>% 
    mutate(byear = 1800) %>% 
    mutate(dyear = byear + floor(death_age))

sim_data <- sim_data %>% 
    filter(death_age > 65)
  
lm_model2 <- lm(death_age~sex, data = sim_data)
  
tibble(coef = summary(lm_model2)$coefficients["sex","Estimate"],
       se = summary(lm_model2)$coefficients["sex","Std. Error"],
       start_year = start_year,
       window_width = window_width,
       n = nrow(sim_data_trunc)) 

data <- bind_rows(results) %>% 
  ungroup() %>% 
  mutate(t = coef/se) %>% 
  mutate(se = se/0.0240,
         t = t / 41.08333,
         coef = coef/0.986)

plota <- ggplot(data, aes(x = start_year - 1800 , y = window_width)) + 
  geom_tile(aes(fill = se)) + 
  # scale_fill_distiller(palette = "YlGnBu") + 
  scale_fill_viridis_c(option = "magma") + 
  cowplot::theme_minimal_hgrid(15) +
  labs(y = "Width of Window (Years)",
       x = "Starting Age",
       fill = "SE / SE (untruncated)",
       title = "Standard Errror",
       caption = "") + 
  theme(legend.position = "bottom", 
        legend.key.width=unit(2.5, "cm"))

plotb <- ggplot(data, aes(x = start_year - 1800 , y = window_width)) + 
  geom_tile(aes(fill = coef)) + 
  # scale_fill_distiller(palette = "YlGnBu") + 
  scale_fill_viridis_c(option = "magma") + 
  cowplot::theme_minimal_hgrid(15) + 
  labs(y = "Width of Window (Years)",
       x = "Starting Age",
       fill = "Coef / Coef (untruncated)",
       title = "Regression Coefficient") + 
  theme(legend.position = "bottom",
        legend.key.width=unit(2.5, "cm"))

plotc <- ggplot(data, aes(x = start_year - 1800, y =  window_width )) + 
  geom_tile(aes(fill = t)) + 
  # scale_fill_distiller(palette = "YlGnBu") + 
  scale_fill_viridis_c(option = "magma") + 
  cowplot::theme_minimal_hgrid(15) + 
  labs(y = "Width of Window (Years)",
       x = "Starting Age",
       fill = "T-Stat / T-Stat (untruncated)",
       title = "T-Statistic") + 
  theme(legend.position = "bottom",
        legend.key.width=unit(2.5, "cm"))

## create plot 
plot_sim <- cowplot::plot_grid(plotb, plota, plotc, ncol = 1, labels = "auto")

title <- ggdraw() + 
  draw_label(
    "OLS under Double-Truncation",
    fontface = 'bold',
    x = 0,
    hjust = 0,
    vjust = 2.5,
    size = 22
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 0)
  )

plot_sim_title <- plot_grid(
  title, plot_sim,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

## save plot 
ggsave(plot_sim_title, filename = "../figures/simulated_window_widths.pdf", height = 17, width = 10)
```

```{r}
sim_data <- gompertztrunc::gompertztrunc_simu(n=36500, formula = death_age ~ sex, coefs = c('sex'=-0.2), dummy=c(TRUE)) %>% 
    mutate(byear = 1800) %>% 
    mutate(dyear = byear + floor(death_age))

sim_data <- sim_data %>% 
    filter(death_age > 65)

gompertz_mle(death_age ~ sex, data = sim_data, left_trunc = 1865, right_trunc = 1898)
```

```{r}
results <- list()
i = 1

for (window_width in c(6:30)) {

  
  sim_data <- gompertztrunc::gompertztrunc_simu(n=200000, formula = death_age ~ sex, coefs = c('sex'=-0.8), dummy=c(TRUE)) %>% 
    mutate(byear = 1800) %>% 
    mutate(dyear = byear + floor(death_age))
  
  sim_data_trunc <- sim_data %>% 
    filter(dyear >= 1868 & dyear <= 1868 + window_width)
  
  adj_factor <- 200000/nrow(sim_data_trunc)
  
  sim_data <- gompertztrunc::gompertztrunc_simu(n = adj_factor*200000, formula = death_age ~ sex, coefs = c('sex'=-0.2), dummy=c(TRUE)) %>%
    mutate(byear = 1800) %>% s
    mutate(dyear = byear + floor(death_age))
  
  sim_data_trunc <- sim_data %>% 
    filter(dyear >= start_year & dyear <= start_year + window_width)
  
gompertz_results <- gompertz_mle(death_age ~ sex, data = sim_data, left_trunc = 1868, right_trunc = 1868 + window_width)$results
  
results[[i]] <- tibble(result = gompertz_results %>% filter(parameter == "sex") %>% summarize(hr_upper - hr_lower) %>% as.numeric(), window_width = window_width)
  
  i = i + 1 
  cat(i)
  
} 

plot_mle <- bind_rows(results) %>%
  ggplot(aes(y = result/4, x = window_width)) + 
  geom_point() + 
  geom_line() + 
  theme_cowplot() + 
  labs(x = "Window Width",
       y = "SE",
       title = "MLE Standard Error")

ggsave(plot_mle, filename = "figures_variance_analyis/standard_error_widths.pdf", height = 5, width = 7)
```

