---
title: "Code to replicate Figure 6"
author: Maria Osborne
---

Summary: This .Rmd file contains code to replicate Figure 6 in "Mortality Modeling of Partially Observed Cohorts Using Administrative Death Records." 

Description of Figure 6: Acceptably wide observation windows. Values are estimated hazard ratios of the education gradient for men born in 1910, using CenSoc-Numident data, with different combinations of truncation limits. The best estimate of the hazard ratio is 0.97, which is computed using the widest observation window possible (17 years). Light gray tiles are observation windows where the model captures the best estimate of the hazard ratio in a 95\% confidence interval. Estimates inside the black outline indicate that the truncation window contains the modal age at death, which is 84 years in these data. This experiment indicates that truncation windows of approximately 10-12 years or more usually produce reliable estimates. Windows as narrow as 8-9 years may also be sufficient for estimation, if the data contain the mode of the empirical mortality distribution. 


```{r}
## Figure 6: HR estimates with shifting observation window

## Packages
library(tidyverse)
library(gompertztrunc)
library(data.table)
library(here)
source("helpers.R")


## Read in Data
censoc_num <- fread(here("data/censoc_numident_v2.1_linked_extract.csv"))

## Limit sample
censoc_num <- censoc_num %>% filter(
  link_abe_exact_conservative == 1, byear == 1910,
  EDUCD != 0 & EDUCD != 999, sex == 1
)

## create education variable
censoc_num <- censoc_num %>%
  recode_education()


## create dataframe to store estimates in
df_real_1910 <- data.frame()

## Loop over observation bounds
for (start_year in c(1988:2003)) {
  for (end_year in c((start_year + 2):2005)) {
    
    data_truncated <- censoc_num %>%
      filter(dyear %in% start_year:end_year)

    window_length_yrs <- (end_year - start_year) + 1
    min_age <- min(data_truncated$death_age) + 1
    max_age <- max(data_truncated$death_age) - 1
    window_length_age <- (max_age - min_age) + 1

    # run gompertzmle()
    model <- gompertztrunc::gompertz_mle(
      formula = death_age ~ educ_yrs, data = data_truncated,
      left_trunc = start_year, right_trunc = end_year
    )

    ests <- model$results %>% filter(parameter == "educ_yrs")
    gb <- (model$results %>% filter(parameter == "gompertz_b"))$coef
    gm <- (model$results %>% filter(parameter == "gompertz_mode"))$coef
    did_converge <- model$optim_fit$convergence == 0

    ests <- ests %>% mutate(
      start_year = start_year, end_year = end_year, convergence = did_converge,
       min_age = min_age, max_age = max_age,
      wl_year = window_length_yrs, wl_age = window_length_age,
      gompertz_b = gb, gompertz_mode = gm
    )

    df_real_1910 <- rbind(df_real_1910, ests)
  }
}

## "True" (Best) estimate of hazard ratio (broadest age band)
true_hr_1910 <- 0.9673656

## add mode boolean
df_real_1910 <- df_real_1910 %>%
  mutate(is_bad = (true_hr_1910 < hr_lower | true_hr_1910 > hr_upper)) %>%
  mutate(contains_mode = min_age <= 84 & max_age >= 84) %>%
  mutate(is_bad = ifelse(is_bad == TRUE, "No", "Yes")) %>%
  mutate(is_bad = relevel(as.factor(is_bad), ref = "Yes"))


## plot 1910
df_real_1910 %>%
  ggplot(aes(x = as.factor(min_age), y = as.factor(wl_age))) +
  geom_tile(color = "white", lwd = 0.7, aes(fill = is_bad)) + # fill = 'gray85') +
  geom_text(aes(label = round(hr, 2)), size = 3.2, family = "serif") +
  theme_bw() +
  scale_fill_manual(values = c("grey90", "grey65")) +
  theme( # line = element_blank(),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) +
  labs(x = "Starting Age", y = "Width of Window (Years)", fill = "Window \nCaptures \nBest \nEstimate")

## save file
ggsave(
  filename = here("figures/fig6-window_numident.png"),
  height = 5, width = 8
)
```
