---
title: "Table 1 — Education Table"
author: Casey Breen
---

Summary: This .Rmd file contains code to replicate the "This Study" results in Table 1 of "Mortality Modeling of Partially Observed Cohorts Using Administrative Death Records." 

Description of Table 1: Estimates of education gradient across studies

```{r}
## library packages
library(data.table)
library(tidyverse)
library(broom)
library(socviz)
library(cowplot)
library(ggsci)
library(here)
source("helpers.R")
```


```{r}
## read in prelinked CenSoc datasets and filter to "conservative" matches
dmf <- fread(here("data/censoc_dmf_v2.1_linked_extract.csv")) %>%
  filter(link_abe_exact_conservative == 1)

numident <- fread(here("data/censoc_numident_v2.1_linked_extract.csv")) %>%
  filter(link_abe_exact_conservative == 1)
```


```{r}
## numident results 
numident_results <-  gompertztrunc::gompertz_mle(death_age ~ educ_yrs, data = numident %>% filter(byear %in% 1910:1920 & sex == 1), left_trunc = 1988, right_trunc = 2005, weights = weight_conservative)

gompertztrunc::convert_hazards_to_ex(numident_results$results, use_model_estimates = T, age = 35)
  
## dmf results 
dmf_results <- gompertztrunc::gompertz_mle(death_age ~ educ_yrs, data = dmf %>% filter(byear %in% 1910:1920), left_trunc = 1975, right_trunc = 2005, weights = weight_conservative)

gompertztrunc::convert_hazards_to_ex(dmf_results$results, M = 74.87271928, b = 0.08175947, age = 35)
```




